kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
     global:
     templates:
     - '/etc/prometheus/prometheus.rules'
       smtp_auth_username: AKIARIGS3RKBDID4TH3N
       smtp_auth_password: BPrZcaGNZHWPqXZIgTTgNA7f/JOjmkexHguVVWfoUm8P
       smtp_require_tls: yes
       smtp_smarthost: email-smtp.us-east-1.amazonaws.com:587
       smtp_from: delhivery-infrasupport@delhivery.com (Monitoring-Alerts)
     route:
       group_by: ['alertname', 'Project','instance', 'severity', 'Environment', 'Name', 'subject', 'job', 'nodename']
       group_wait: 30s
       group_interval: 5m
       repeat_interval: 30m
       receiver: Delhivery-Infrasupport
